on:
  push:
    branches: [ 'main' ]

jobs:
  factions-alpha:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build project
        run: ./gradlew jar
      - name: Deploy project to artifactory
        run: ./gradlew publish
      - name: Deploy to remote servers
        run: |
          sh /home/cloud/scripts/github/deploy.sh build/libs/factions-alpha.jar